### ISSUE TITLE
Reporte de entrevista

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equipo-1-1#1]
Subí reporte de practica 
[PRACTICA ENTREVISTA UNIDAD 3.pdf](https://github.com/user-attachments/files/17562106/PRACTICA.ENTREVISTA.UNIDAD.3.pdf)

**Comment by josealfredo79** [comment]
Calificacion...???

**Comment by AmeliReyesHernandez** [comment]
De acuerdo a la rubrica cumple con todos los criterios y tiene el 30%

**Comment by josealfredo79** [comment]
La calificacion final debe ser de 30% Por favor...Revisado y bien hecho...
